#!/usr/bin/env python3
"""
Test suite for montreal-housing-analysis
Auto-generated by Engineering Agency V3
"""

import pytest
import pandas as pd
from pathlib import Path
import sys

# Add current directory to path
sys.path.insert(0, str(Path(__file__).parent))

# Import main analysis module
import analysis


class TestDataLoading:
    """Test data loading and validation"""
    
    def test_csv_files_exist(self):
        """Verify required CSV files are present"""
        data_dir = Path(__file__).parent / "data"
        assert data_dir.exists(), "Data directory should exist"
        
        csv_files = list(data_dir.glob("*.csv"))
        assert len(csv_files) > 0, "At least one CSV file should exist"
    
    def test_data_loading_functions(self):
        """Test that data loading functions are defined"""
        # Check for common data loading patterns
        module_functions = dir(analysis)
        
        # Should have some data processing capability
        assert len(module_functions) > 0, "Module should have functions defined"


class TestDataProcessing:
    """Test data processing logic"""
    
    def test_pandas_dataframe_operations(self):
        """Test basic pandas operations work"""
        # Create sample data
        sample_data = pd.DataFrame({
            'price': [100000, 200000, 300000],
            'bedrooms': [1, 2, 3],
            'bathrooms': [1, 1, 2]
        })
        
        # Test basic operations
        assert len(sample_data) == 3
        assert 'price' in sample_data.columns
        assert sample_data['price'].mean() == 200000
    
    def test_data_validation(self):
        """Test data validation logic"""
        # Sample invalid data
        invalid_data = pd.DataFrame({
            'price': [-1000, None, 200000],
            'bedrooms': [1, 2, 3]
        })
        
        # Price should not be negative
        has_negative = (invalid_data['price'] < 0).any()
        assert isinstance(has_negative, bool), "Validation should return boolean"


class TestAnalysisOutputs:
    """Test that analysis produces expected outputs"""
    
    def test_output_directory_structure(self):
        """Verify output directory exists or can be created"""
        output_dir = Path(__file__).parent / "output"
        
        # Either exists or can be created
        if not output_dir.exists():
            output_dir.mkdir(exist_ok=True)
        
        assert output_dir.exists(), "Output directory should be accessible"
    
    def test_readme_exists(self):
        """Verify README documentation exists"""
        readme = Path(__file__).parent / "README.md"
        assert readme.exists(), "README.md should exist"


class TestStatisticalFunctions:
    """Test statistical calculations"""
    
    def test_basic_statistics(self):
        """Test basic statistical operations"""
        data = pd.Series([100, 200, 300, 400, 500])
        
        mean = data.mean()
        median = data.median()
        
        assert mean == 300, "Mean calculation should work"
        assert median == 300, "Median calculation should work"
    
    def test_correlation_analysis(self):
        """Test correlation calculations"""
        df = pd.DataFrame({
            'x': [1, 2, 3, 4, 5],
            'y': [2, 4, 6, 8, 10]
        })
        
        corr = df['x'].corr(df['y'])
        assert corr == 1.0, "Perfect correlation should be 1.0"


# Smoke test - ensure module can be imported without errors
def test_module_imports():
    """Verify all required modules can be imported"""
    import pandas
    import matplotlib
    import seaborn
    import numpy
    
    assert pandas.__version__ >= "2.0"
    assert numpy.__version__ >= "1.24"


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
